name: Publish to PyPI

on:
  release:
    types: [manual, published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install -r requirements.txt

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION_CODE=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV

      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USER }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          PACKAGE_VERSION: ${{ env.VERSION_CODE }}
        run: |
            sed -i "s/version='.*'/version='${VERSION_CODE}'/" setup.py  # Update version in setup.py
            python setup.py sdist bdist_wheel
            twine upload dist/*
